from enum import Enum


class DayCount(Enum):
    ACTUAL_360 = "ACTUAL_360"
    ACTUAL_365 = "ACTUAL_365"
    ACTUAL_360_ADJUSTED = "ACTUAL_360_ADJUSTED"
    ACTUAL_ACTUAL_ICMA = "ACTUAL_ACTUAL_ICMA"
    ACTUAL_ACTUAL_ISDA = "ACTUAL_ACTUAL_ISDA"
    THIRTY_360 = "THIRTY_360"
