from enum import Enum


class Frequency(Enum):
    ANNUALLY = "ANNUALLY"
    SEMIANNUALLY = "SEMIANNUALLY"
    EVERY_FOURTH_MONTH = "EVERY_FOURTH_MONTH"
    QUARTERLY = "QUARTERLY"
    BIMONTHLY = "BIMONTHLY"
    MONTHLY = "MONTHLY"
    EVERY_FOURTH_WEEK = "EVERY_FOURTH_WEEK"
    BIWEEKLY = "BIWEEKLY"
    WEEKLY = "WEEKLY"
    DAILY = "DAILY"
